Repository EarthGardener/EarthGardener-Android, pull requests merged in 2022-03, with the labels that each got.

#31 Feature/26 signup refactor
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/DataSourceModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/RepositoryModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/ViewModelModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/mypage/modifyProfile/ModifyProfileActivity.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/emailpw/EmailPwFragment.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/emailpw/viewModel/CheckEmailViewModel.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/nickname/NickNameFragment.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/retrofit/RetrofitClient.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/retrofit/SignUpResponse.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/retrofit/SignUpRetrofitInterface.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/viewModel/SignUpViewModel.kt
  EarthGardener/app/src/main/res/layout/fragment_email_pw.xml
Labels: junghyun🎠, FEAT, In Progress

#41 [FIX] token 저장
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/login/viewModel/SignInViewModel.kt
Labels: junghyun🎠

#43 Refactor/42 navigation component
  EarthGardener/.idea/misc.xml
  EarthGardener/app/build.gradle
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/main/MainActivity.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/util/NavigationUtil.kt
  EarthGardener/app/src/main/res/layout/activity_login.xml
  EarthGardener/app/src/main/res/layout/activity_main.xml
  EarthGardener/app/src/main/res/layout/activity_modify_profile.xml
  EarthGardener/app/src/main/res/layout/activity_modify_pw.xml
  EarthGardener/app/src/main/res/layout/activity_post_form.xml
  EarthGardener/app/src/main/res/layout/activity_sign_up.xml
  EarthGardener/app/src/main/res/layout/fragment_email_pw.xml
  EarthGardener/app/src/main/res/layout/fragment_home.xml
  EarthGardener/app/src/main/res/layout/fragment_my_page.xml
  EarthGardener/app/src/main/res/layout/fragment_nick_name.xml
  EarthGardener/app/src/main/res/layout/fragment_post.xml
  EarthGardener/app/src/main/res/menu/menu_main_bottom_navigation_view.xml
  EarthGardener/app/src/main/res/navigation/nav_graph_bottom.xml
  EarthGardener/build.gradle
  EarthGardener/gradle/wrapper/gradle-wrapper.properties
Labels: Done, jaesung :fire:, REFACTOR
