Repository EarthGardener/EarthGardener-Android, pull requests merged in 2022-02, with the labels that each got.

#4 Feature/3 add colors
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  EarthGardener/.idea/misc.xml
  EarthGardener/.idea/vcs.xml
  EarthGardener/app/src/main/res/drawable/selector_bottom_navi_color.xml
  EarthGardener/app/src/main/res/values/colors.xml
Labels: Done, jaesung :fire:

#6 Feature/2 post post form UI
  EarthGardener/.idea/misc.xml
  EarthGardener/app/src/main/AndroidManifest.xml
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/post/PostFormActivity.kt
  EarthGardener/app/src/main/res/drawable/circle_black_size_1.xml
  EarthGardener/app/src/main/res/drawable/circle_dark_green_border_2.xml
  EarthGardener/app/src/main/res/drawable/circle_light_green_border_2.xml
  EarthGardener/app/src/main/res/drawable/circle_light_light_green_border_2.xml
  EarthGardener/app/src/main/res/drawable/circle_light_light_light_green_border_2.xml
  EarthGardener/app/src/main/res/drawable/circle_primary_green_border_2.xml
  EarthGardener/app/src/main/res/drawable/circle_yellow_border_2.xml
  EarthGardener/app/src/main/res/drawable/ic_left_arrow.xml
  EarthGardener/app/src/main/res/drawable/ic_plus.xml
  EarthGardener/app/src/main/res/drawable/ic_right_arrow.xml
  EarthGardener/app/src/main/res/drawable/rectangle_gray_height_1.xml
  EarthGardener/app/src/main/res/drawable/rectangle_light_gray_border_1.xml
  EarthGardener/app/src/main/res/drawable/rectangle_light_gray_radius_12.xml
  EarthGardener/app/src/main/res/drawable/rectangle_lightgreen_radius_30.xml
  EarthGardener/app/src/main/res/drawable/rectangle_mint_radius_20.xml
  EarthGardener/app/src/main/res/drawable/rectangle_primary_green_radius_20.xml
  EarthGardener/app/src/main/res/drawable/rectangle_secondary_green_border_radius_12.xml
  EarthGardener/app/src/main/res/drawable/selector_secondary_green_save.xml
  EarthGardener/app/src/main/res/layout/activity_post_form.xml
  EarthGardener/app/src/main/res/layout/fragment_post.xml
  EarthGardener/app/src/main/res/layout/item_post_daily.xml
  EarthGardener/app/src/main/res/values/strings.xml
Labels: chaeyeong🌊, UI, Done

#10 Feature/5 splash
  EarthGardener/.idea/misc.xml
  EarthGardener/app/build.gradle
  EarthGardener/app/src/main/AndroidManifest.xml
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/MainActivity.kt
  EarthGardener/app/src/main/res/drawable/ic_logo_splash.png
  EarthGardener/app/src/main/res/values/strings.xml
  EarthGardener/app/src/main/res/values/themes.xml
Labels: UI, Done, jaesung :fire:

#9 Feature/8 mypage UI
  EarthGardener/app/build.gradle
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/mypage/MyPageFragment.kt
  EarthGardener/app/src/main/res/drawable/circle_white_size_25.xml
  EarthGardener/app/src/main/res/drawable/rectangle_light_gray_width_60_height_25_radius_15.xml
  EarthGardener/app/src/main/res/drawable/rectangle_primary_green_width_60_height_25_radius_15.xml
  EarthGardener/app/src/main/res/drawable/selector_switch_track.xml
  EarthGardener/app/src/main/res/layout/fragment_my_page.xml
  EarthGardener/app/src/main/res/values/strings.xml
Labels: junghyun🎠, UI, Done

#7 FEATURE/1 login signup UI
  EarthGardener/app/src/main/AndroidManifest.xml
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/MainActivity.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/login/LoginActivity.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/SignUpActivity.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/emailpw/EmailPwFragment.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/nickname/NickNameFragment.kt
  EarthGardener/app/src/main/res/drawable-v24/ic_gallery.png
  EarthGardener/app/src/main/res/drawable/rectangle_light_gray_radius_30.xml
  EarthGardener/app/src/main/res/drawable/rectangle_light_gray_width_1.xml
  EarthGardener/app/src/main/res/drawable/rectangle_primary_green_radius_30.xml
  EarthGardener/app/src/main/res/layout/activity_login.xml
  EarthGardener/app/src/main/res/layout/activity_sign_up.xml
  EarthGardener/app/src/main/res/layout/fragment_email_pw.xml
  EarthGardener/app/src/main/res/layout/fragment_nick_name.xml
  EarthGardener/app/src/main/res/values/strings.xml
Labels: junghyun🎠, UI, Done

#14 [UI] 홈 화면 레이아웃 구성 #12
  EarthGardener/.idea/misc.xml
  EarthGardener/app/src/main/res/drawable/bg_home.xml
  EarthGardener/app/src/main/res/drawable/selector_edit_text_tracker_green.xml
  EarthGardener/app/src/main/res/layout/dialog_tree_name.xml
  EarthGardener/app/src/main/res/layout/fragment_home.xml
  EarthGardener/app/src/main/res/values/strings.xml
Labels: UI, Done, jaesung :fire:

#16 Feature/13 user view logic
  EarthGardener/app/src/main/AndroidManifest.xml
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/api/LoginService.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/email/CheckEmailDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/email/CheckEmailRemoteDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/nickname/CheckNicknameDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/nickname/CheckNicknameRemoteDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/signup/SignUpDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/signup/SignUpRemoteDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/mapper/CheckEmailMapper.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/mapper/CheckNicknameMapper.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/mapper/SignUpMapper.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/model/response/ResCheckEmailSuccessData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/model/response/ResCheckNicknameSuccessData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/model/response/ResSignUpSuccessData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/repository/CheckEmailRepositoryImpl.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/repository/CheckNicknameRepositoryImpl.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/repository/SignUpRepositoryImpl.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/DataSourceModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/EarthGardenerApplication.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/NetworkModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/RepositoryModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/ViewModelModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/XAccessTokenInterceptor.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/email/CheckEmailData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/email/CheckEmailRepository.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/nickname/CheckNicknameData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/nickname/CheckNicknameRepository.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/signup/SignUpData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/signup/SignUpRepository.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/login/LoginActivity.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/SignUpActivity.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/emailpw/EmailPwFragment.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/emailpw/viewModel/CheckEmailViewModel.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/login/LoginRequest.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/login/LoginResponse.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/login/LoginRetrofitInterface.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/nickname/NickNameFragment.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/nickname/viewModel/CheckNicknameViewModel.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/retrofit/SignUpRequest.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/retrofit/SignUpResponse.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/retrofit/SignUpRetrofitClient.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/retrofit/SignUpRetrofitInterface.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/viewModel/SignUpViewModel.kt
  EarthGardener/app/src/main/res/xml/network_security_config.xml
Labels: junghyun🎠, FEAT, Done

#18 Feature/15 home logic
  EarthGardener/.idea/deploymentTargetDropDown.xml
  EarthGardener/.idea/misc.xml
  EarthGardener/app/src/main/AndroidManifest.xml
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/api/TreeService.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/tree/TreeInfoDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/tree/TreeInfoRemoteDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/mapper/TreeInfoMapper.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/model/response/tree/ResTreeInfoSuccessData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/repository/tree/TreeInfoRepositoryImpl.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/sharedpref/EarthGardenerSharedPreference.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/DataSourceModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/EarthGardenerApplication.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/NetworkModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/RepositoryModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/ViewModelModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/XAccessTokenInterceptor.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/model/tree/TreeInfoSuccessData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/repository/tree/TreeInfoRepository.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/home/HomeFragment.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/main/MainActivity.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/main/viewmodel/MainViewModel.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/login/LoginActivity.kt
  EarthGardener/app/src/main/res/drawable/ic_edit.xml
  EarthGardener/app/src/main/res/drawable/img_tree_level_1.xml
  EarthGardener/app/src/main/res/drawable/img_tree_level_2.xml
  EarthGardener/app/src/main/res/drawable/img_tree_level_3.xml
  EarthGardener/app/src/main/res/drawable/img_tree_level_4.xml
  EarthGardener/app/src/main/res/drawable/img_tree_level_5.xml
  EarthGardener/app/src/main/res/layout/activity_main.xml
  EarthGardener/app/src/main/res/layout/fragment_home.xml
  EarthGardener/app/src/main/res/values/strings.xml
Labels: FEAT, Done, jaesung :fire:

#20 Feature/17 chore
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/EarthGardenerApplication.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/NetworkModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/mypage/MyPageFragment.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/mypage/MyPageRetrofitInterface.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/mypage/retrofit/Data.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/mypage/retrofit/ProfileResponse.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/login/LoginActivity.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/emailpw/EmailPwFragment.kt
  EarthGardener/app/src/main/res/layout/fragment_my_page.xml
Labels: junghyun🎠, CHORE, Done

#21 [UI] #19 - 나무 이름 변경 다이얼로그 구현 완료
  EarthGardener/.idea/misc.xml
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/tree/TreeNameDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/tree/TreeNameRemoteDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/mapper/TreeMapper.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/model/request/ReqTreeNameSuccessData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/model/response/tree/ResTreeNameSuccessData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/repository/tree/TreeInfoRepositoryImpl.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/repository/tree/TreeNameRepositoryImpl.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/DataSourceModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/RepositoryModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/ViewModelModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/model/tree/TreeNameSuccessData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/repository/tree/TreeNameRepository.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/home/HomeFragment.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/main/viewmodel/MainViewModel.kt
  EarthGardener/app/src/main/res/drawable/rectangle_primary_green_radius_12.xml
  EarthGardener/app/src/main/res/layout/dialog_tree_name.xml
Labels: FEAT, Done, jaesung :fire:

#22 Feature/11 post form activity
  EarthGardener/.idea/misc.xml
  EarthGardener/app/src/main/AndroidManifest.xml
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/api/PostService.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/post/PostDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/post/PostLocalDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/post/PostRemoteDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/mapper/PostFormCheckListData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/mapper/PostListsData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/model/request/ReqPostFormData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/model/response/ResChecklistData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/model/response/ResPostData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/repository/PostRepositoryImpl.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/DataSourceModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/NetworkModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/RepositoryModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/ViewModelModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/post/CheckListData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/post/PostListData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/post/PostRepository.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/main/viewmodel/MainViewModel.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/post/PostFormActivity.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/post/PostFragment.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/post/PostListAdapter.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/post/viewmodel/PostFormViewModel.kt
  EarthGardener/app/src/main/res/drawable/ic_write.xml
  EarthGardener/app/src/main/res/layout/activity_post_form.xml
  EarthGardener/app/src/main/res/layout/item_post_daily.xml
  EarthGardener/app/src/main/res/values/strings.xml
  EarthGardener/app/src/main/res/values/themes.xml
Labels: FEAT, chaeyeong🌊, In Progress

#30 Feature/27 put profile
  EarthGardener/.idea/misc.xml
  EarthGardener/app/src/main/AndroidManifest.xml
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/api/ProfileService.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/profile/modify/ModifyProfileDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/datasource/profile/modify/ModifyProfileRemoteDataSource.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/mapper/profile/ModifyProfileMapper.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/model/response/profile/ResModifyProfileSuccessData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/data/repository/profile/ModifyProfileRepositoryImpl.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/DataSourceModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/RepositoryModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/di/ViewModelModule.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/profile/modify/ModifyProfileData.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/domain/profile/modify/ModifyProfileRepository.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/mypage/MyPageFragment.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/mypage/modifyProfile/ModifyProfileActivity.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/mypage/modifyProfile/viewmodel/ModifyProfileViewModel.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/nickname/NickNameFragment.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/retrofit/RetrofitClient.kt
  EarthGardener/app/src/main/java/team/gdsc/earthgardener/presentation/user/signup/retrofit/SignUpRequest.kt
  EarthGardener/app/src/main/res/drawable/ic_close.xml
  EarthGardener/app/src/main/res/layout/activity_modify_profile.xml
  EarthGardener/app/src/main/res/layout/fragment_my_page.xml
  EarthGardener/app/src/main/res/values/strings.xml
Labels: junghyun🎠, FEAT, Done
